// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebAppServer.Contexts;

namespace WebAppServer.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20220421212819_six")]
    partial class six
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppServer.Models.ActualTask", b =>
                {
                    b.Property<int>("ActualTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CareSchedule_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Palet_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("RealizationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("User_Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ActualTaskId");

                    b.ToTable("ActualTask");
                });

            modelBuilder.Entity("WebAppServer.Models.CareSchedule", b =>
                {
                    b.Property<int>("CareScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PaletPlantsType_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PriorityNumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("TimeOfCare")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TypeOfCare_Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CareScheduleId");

                    b.ToTable("CareSchedule");
                });

            modelBuilder.Entity("WebAppServer.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("WebAppServer.Models.Palet", b =>
                {
                    b.Property<int>("PaletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfPlanting")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PaletNumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PaletPlantsType_Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PaletId");

                    b.ToTable("Palet");
                });

            modelBuilder.Entity("WebAppServer.Models.PaletPlantsType", b =>
                {
                    b.Property<int>("PaletPlantsTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaletPlantsTypeName")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("PaletPlantsTypeId");

                    b.ToTable("PaletPlantsType");
                });

            modelBuilder.Entity("WebAppServer.Models.TypeOfCare", b =>
                {
                    b.Property<int>("TypeOfCareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeOfCareName")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("TypeOfCareId");

                    b.ToTable("TypeOfCare");
                });

            modelBuilder.Entity("WebAppServer.Models.UserCategory", b =>
                {
                    b.Property<int>("UserCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserCategoryName")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("UserCategoryId");

                    b.ToTable("UserCategory");
                });

            modelBuilder.Entity("WebAppServer.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Company_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Mail")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<int>("UserCategory_Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
